### PR TITLE
upgraded deps, fixed warning

### PR DESCRIPTION
**Pull request by athanclark**
Hi again!

I just had to adjust the lower bound on some of the deps in this library to get it up-to-speed. Also, there was a warning in Data.Vec that's been around for some time; I hope you don't mind me editing it.

Thank you for this library, please let me know if you'd need anything else from me to get it pushed upstream!

### CODE REVIEW

**Comment by athanclark** [comment]
@bodil ping! I got the tests working; there wasn't any changes to the API - just a precedence issue with `::`.

**Comment by athanclark** [comment]
@bodil Hey sorry for pestering, I just really need progress made on this end, because it's a prerequisite to purescript-arraybuffer; sized vectors are great for avoiding a size argument during serialization of binary data.

**Comment by bodil** [comment]
Tagging a release now, but as you can tell my maintainership of my PS stuff is spotty at best. If your work depends on this, would you like me to add you as a maintainer?

**Comment by athanclark** [comment]
@bodil Heck yeah! I'll take care of it :)

**Comment by bodil** [comment]
Done!

**Pull request merged**
